services:
  - type: web
    name: cvmatch-web
    runtime: docker
    plan: starter
    healthCheckPath: /
    envVars:
      - key: APP_DEBUG
        value: "false"
      - key: DB_HOST
        fromDatabase:
          name: cvmatch-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cvmatch-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: cvmatch-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: cvmatch-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: cvmatch-db
          property: password
      - key: IA_SERVICE_URL
        value: "https://cvmatch-python.onrender.com"

  - type: web
    name: cvmatch-python
    runtime: docker
    plan: starter
    buildCommand: "cd python-service && pip install -r requirements.txt"
    startCommand: "cd python-service && python app.py"
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: PORT
        value: "5000"

databases:
  - name: cvmatch-db
    plan: starter
    databaseName: cvmatch_db
    engine: mysql
    version: "8"
