services:
  - type: web
    name: cvmatch-web
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_DEBUG
        value: "false"
      - key: DB_HOST
        fromDatabase:
          name: cvmatch-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cvmatch-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: cvmatch-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: cvmatch-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: cvmatch-db
          property: password
      - key: DB_ENGINE
        value: "pgsql"
      - key: IA_SERVICE_URL
        value: "http://localhost:5000"
      - key: DEEPSEEK_API_URL
        value: "https://api.deepseek.ai"
      - key: DEEPSEEK_API_KEY
        sync: false

databases:
  - name: cvmatch-db
    plan: basic-256mb
    postgresMajorVersion: "15"
    databaseName: cvmatch_db
